@startuml
left to right direction
hide stereotype
skinparam usecase {
    BackgroundColor<<Abuse>> Black
    FontColor<<Abuse>> White
    BorderColor<<Abuse>> Black
}

actor "User" as User
actor "Attacker" as Attacker

usecase "Import Credentials" as UC_Import
usecase "Export Credentials" as UC_Export
    
usecase "File Schema Validation" as UC_Validate
usecase "Export Encryption / Password" as UC_EncExport

usecase "Malicious File Upload" as AC_Upload <<Abuse>>
usecase "Export Data Leakage" as AC_Leak <<Abuse>>

User --> UC_Import
User --> UC_Export

UC_Import ..> UC_Validate : <<includes>>
UC_Export ..> UC_EncExport : <<includes>>

UC_Validate ..> AC_Upload : <<mitigates>>
UC_EncExport ..> AC_Leak : <<mitigates>>

UC_Import <.. AC_Upload : <<threatens>>
UC_Export <.. AC_Leak : <<threatens>>

AC_Upload <-- Attacker
AC_Leak <-- Attacker
@enduml