# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections:
# Enforce SSL with client certificate authentication (cert) for all network connections
hostssl all             all             0.0.0.0/0               cert
hostssl all             all             ::0/0                   cert

# Explicitly reject all non-SSL connections
hostnossl all           all             0.0.0.0/0               reject
hostnossl all           all             ::0/0                   reject
